name: Deploy OrtoDio

on:
  push:
    branches:
      - ortodio

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "OrtoDio deploy ok"


        
